# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3441159a46caadc5b8ec9a1b35830df7875ddfd36443c8612e025b4c47446f67f933245736730776766b8f6f56428408aa3c222d9b5160194538232814c82595

test:
  secret_key_base: 2a5649a1c98ba9341175b8847d6e71b9269c3b7bec4f119828e4609ecd253f3f250749b6cf5812a72503d4cfef653470a3328d1ed9c04a79ef83ea589789f427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
